# Generated by Django 3.1.1 on 2022-05-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='Facility',
            new_name='facility',
        ),
        migrations.AddField(
            model_name='availability',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availability',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
