# Generated by Django 3.1.1 on 2022-05-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220515_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='available',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='total',
        ),
    ]
